version: '3.8'

services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  milvus:
    image: milvusdb/milvus:v2.2.11
    environment:
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      # configure other env vars as needed
    ports:
      - "19530:19530"   # gRPC
      - "9091:9091"     # HTTP
    depends_on:
      - minio

volumes:
  minio_data:
